name: Cross Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-platforms:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Run tests
        run: cargo test --verbose
      
      - name: Build
        run: cargo build --release
      
      - name: Run basic functionality test
        run: |
          # Create a test directory with some files
          mkdir -p test-project
          cd test-project
          touch test.py
          touch test.js
          touch Cargo.toml
          touch composer.json
          
          # Test basic functionality
          ../target/release/codeguard --help
          ../target/release/codeguard --version
          ../target/release/codeguard . 