name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Build
        run: cargo build --release
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/codeguard
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install cargo-deb
        run: cargo install cargo-deb
      
      - name: Create Debian package
        run: cargo deb
      
      - name: Upload Debian package
        uses: softprops/action-gh-release@v1
        with:
          files: target/debian/codeguard_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 